spring:
  application:
    name: Digital active

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: 01032002ama
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # PAY ATTENTION, BE CAUTIOUS!!!
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path:/swagger-ui.html

application:
  rca:
    private-key: ${PRIVATE_KEY_PATH:classpath:keys/private_key.pem}
    public-key: ${PUBLIC_KEY_PATH:classpath:keys/public_key.pem}

app:
  auth:
    login-url: /api/auth/v1/login
    user-url: /api/users/v1

queue: Queue
exchange: Direct
key: user.create

local:
  host: http://localhost:8080

telegram:
  BOT_TOKEN: ${BOT_TOKEN:token}
  BOT_NAME: ${BOT_NAME:name}

management:
  server:
    port: 8081
  health:
    ldap:
      enabled: off
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
    enabled-by-default: false
  endpoint:
    web:
      exposure:
        include: "*"
    info:
      enabled: true
    env:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: "readinessState"
        liveness:
          include: "livenessState"
      enabled: true
      show-details: always
    prometheus:
      enabled: true
