spring:
  application:
    name: Digital active



  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: 01032002ama
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # PAY ATTENTION, BE CAUTIOUS!!!
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path:/swagger-ui.html

application:
  rca:
    private-key: ${PRIVATE_KEY_PATH:classpath:keys/private_key.pem}
    public-key: ${PUBLIC_KEY_PATH:classpath:keys/public_key.pem}

telegrambots:
  botToken: 7356408169:AAEiZmReGJ14xZXS5E3GCG-welqgiPv-_U8
  botUsername: WebsiteNumber1Bot
#
#  botToken: ${BOT_NAME_PATH:classpath:keys/bot_name}
#  botUsername: ${BOT_TOKEN_PATH:classpath:keys/bot_token}
